---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started

- name: Enable Nginx Service at Boot
  systemd:
    name: nginx
    enabled: yes

- name: Restart Nginx Service
  systemd:
    name: nginx
    state: started

- name: Copy Nginx configuration file
  copy:
    src: "{{ playbook_dir }}/roles/nginx/templates/default.j2"
    dest: "/etc/nginx/sites-enabled/default"
  notify: Restart Nginx
