---
- name: Install haproxy
  apt:
    name: haproxy
    state: present

- name: Add a haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - Restart haproxy
    - Restart haproxy exporter
  tags: containers

- name: Install haproxy exporter
  apt:
    name: prometheus-haproxy-exporter
    state: present

- name: Add args
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy exporter

- name: Start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Start haproxy exporter
  service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: yes