---
- name: Download InfluxDB package
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
    dest: /tmp/influxdb_1.8.10_amd64.deb
    checksum: "sha256:b2ace09231575df7309a41cea6f9dc7ad716fe4389dc06ac04470a14bd411456"

- name: Install InfluxDB package
  apt:
    deb: "/tmp/influxdb_1.8.10_amd64.deb"
  when: ansible_os_family == 'Debian'
  
- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify:
    - Restart InfluxDB

- name: flush
  ansible.builtin.meta: flush_handlers

- name: Ensure InfluxDB is started and enabled
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: yes

- name: Ensure influxd is started and enabled
  ansible.builtin.service:
    name: influxd
    state: started
    enabled: yes

- name: Download Telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb 
    dest: /tmp/telegraf_1.28.2_amd64.deb
    checksum: "sha256:e074b612e863d517d8908107352333933b3a26f1746c9840d6bc2c3d2463df70"

- name: Check if Telegraf is installed
  command: dpkg -l telegraf
  register: telegraf_installed
  ignore_errors: true
  changed_when: false

- name: Install Telegraf if not already installed
  apt:
    deb: /tmp/telegraf_1.28.2_amd64.deb
    state: present
  when: telegraf_installed.rc != 0


# - name: Generate Telegraf configuration
#   command: telegraf config --input-filter syslog --output-filter influxdb > /etc/telegraf/telegraf.conf
#   args:
#     creates: /etc/telegraf/telegraf.conf

- name: Check if Telegraf config contains required sections
  ansible.builtin.shell: 'grep -Eq "^\s*\[\[outputs.influxdb\]\]" /etc/telegraf/telegraf.conf && grep -Eq "^\s*\[\[inputs.syslog\]\]" /etc/telegraf/telegraf.conf'
  ignore_errors: yes
  changed_when: false
  register: telegraf_config_check

- name: Handle Telegraf configuration
  debug:
    msg: "Checking if there were placed correct configs."
  when: telegraf_config_check.rc == 2 

- name: Add Telegraf config section
  ansible.builtin.blockinfile:
    path: /etc/telegraf/telegraf.conf
    block: |
      [[outputs.influxdb]]
        urls = ["{{ influxdb_udp }}"]
        database = "{{ telegraf_db_name }}"

      [[inputs.syslog]]
        server = "udp://:{{ telegraf_udp_port }}"
  # when: telegraf_config_check.rc != 0
  notify:
    - Restart Telegraf

# - name: Create a directory for the exporter binary
#   file:
#     path: /usr/local/bin
#     state: directory
#     owner: prometheus
#     group: prometheus
#     mode: '0755'

- name: Download InfluxDB Stats Exporter binary
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influxdb_stats_exporter
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create a systemd service unit for InfluxDB Stats Exporter
  template:
    src: influxdb-stats-exporter.service.j2 
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify: Reload systemd 

- name: Start and enable InfluxDB Stats Exporter service
  systemd:
    name: prometheus-influxdb-stats-exporter
    enabled: yes
    state: started

