---

# Enabling InfluxDB
- name: Download InfluxDB package
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
    dest: /opt/downloads/influxdb_1.8.10_amd64.deb
    checksum: "sha256:b2ace09231575df7309a41cea6f9dc7ad716fe4389dc06ac04470a14bd411456"

- name: Install InfluxDB package
  apt:
    deb: /opt/downloads/influxdb_1.8.10_amd64.deb
  when: ansible_os_family == 'Debian'
  
- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify:
    - Restart InfluxDB

- name: flush
  ansible.builtin.meta: flush_handlers

- name: Ensure InfluxDB is started and enabled
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: yes

- name: Ensure influxd is started and enabled
  ansible.builtin.service:
    name: influxd
    state: started
    enabled: yes

# Enabling InfluxDB stats exporter
- name: Download InfluxDB Stats Exporter binary
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influxdb_stats_exporter
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create a systemd service unit for InfluxDB Stats Exporter
  template:
    src: influxdb-stats-exporter.service.j2 
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify: Reload systemd 

- name: Start and enable InfluxDB Stats Exporter service
  systemd:
    name: prometheus-influxdb-stats-exporter
    enabled: yes
    state: started

# InfluxDB backup
- name: Create influxdb directory, created and owned by backup
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'
    mode: '0744'

- name: Add an influxdb cron tab
  ansible.builtin.template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup
