- name: Add Grafana APT GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: check port
  ansible.builtin.debug:
    msg: 
      - "{{ hostvars[inventory_hostname].public_url }}"
      - "{{ hostvars[inventory_hostname].ansible_port | regex_search('^[0-9]{2}')  }}"

- name: Copy Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Ensure Grafana service is started and enabled
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Check if the datasource already exists
  uri:
    url: http://localhost:3000/api/datasources/name/Prometheus
    method: GET
    headers:
      Authorization: "Basic SmVzeWEtbzp0b2pp"
    status_code: 200
    validate_certs: no
  ignore_errors: yes
  register: datasource_exists

- name: Configure Grafana datasource if not already configured
  when: datasource_exists.status != 200
  uri:
    url: http://localhost:3000/api/datasources
    method: POST
    body: '{
      "name": "Prometheus",
      "type": "prometheus",
      "url": "http://jesya-o-2:9090/prometheus",
      "access": "proxy",
      "isDefault": true
    }'
    headers:
      Content-Type: "application/json"
      Authorization: "Basic SmVzeWEtbzp0b2pp"
    status_code: 200
    validate_certs: no

# - name: Copy main.json to remote host
#   copy:
#     src: "{{ role_path }}/files/main.json"
#     dest: /var/lib/grafana/main.json

# - name: Create Grafana Dashboard
#   uri:
#     url: http://localhost:3000/api/dashboards/db
#     method: POST
#     body: "{{ lookup('file', '{{ role_path }}/files/main.json') }}"
#     body_format: json
#     headers:
#       Content-Type: "application/json"
#       Authorization: "Basic SmVzeWEtbzp0b2pp"
#     status_code: 200
#     validate_certs: no

# - name: Create Main Dashboard
#   uri:
#     url: http://localhost:3000/api/dashboards/db
#     method: POST
#     user: "{{ grafana_user }}"
#     password: "{{ grafana_pwd }}"
#     body: files/main.json
#   delegate_to: localhost

# - name: Export dashboard
#   community.grafana.grafana_dashboard:
#     grafana_url: http://localhost:3000/api/dashboards/db
#     grafana_user: "{{ grafana_user }}"
#     grafana_password: "{{ grafana_pwd}}"
#     org_id: 1
#     state: export
#     uid: "IIS"
#     path: "/files/main.json"


