---
- name: Create directories for dashboard and datasources
  file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
    recurse: yes
  loop:
    - dashboards
    - datasources

- name: Copy Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  no_log: true
  notify: 
    - Check if Grafana container exists
    - Remove existing Grafana container

- name: flush
  ansible.builtin.meta: flush_handlers

- name: Copy dashboards
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - logging.json
    - mysql.json
  notify: Restart Grafana

- name: Add datasources
  template:
    src: datasources.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasources.yaml
  notify: Restart Grafana

- name: Copy provisioning configuration file to the remote host
  template:
    src: grafana_provisioning.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify: Restart Grafana

- name: Grafana Docker container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    published_ports: "{{ grafana_port }}:3000"
    volumes: /opt/grafana:/etc/grafana
    restart_policy: always
