---
- name: Install uWSGI packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3

- name: Copy uWSGI configuration for AGAMA
  template:
    src: templates/agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  notify: Restart uWSGI service
  no_log: true

- name: uWSGI service
  service:
    name: uwsgi
    state: started
    enabled: true
