---
- name: Init
  hosts: all
  become: yes
  roles:
    - init
  tags: 
    - i

- name: DNS server
  hosts: dns_servers
  become: yes
  roles:
    - bind
  tags:
    - b

- name: Resolver service
  hosts: all
  become: yes
  roles:
    - resolver
  tags: 
    - r

- name: Database server
  hosts: db_servers
  become: yes
  roles: 
    - mysql
  tags:
    - db

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
  tags:
    - a

- name: Nginx
  hosts: all
  become: yes
  roles: 
    - nginx
  tags:
    - n

- name: Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags:
    - p