---
- name: Init
  hosts: all
  become: yes
  roles:
    - init
  tags: 
    - i

- name: DNS server
  hosts: dns_servers
  become: yes
  roles:
    - bind
  tags:
    - b

- name: Resolver service
  hosts: nginx_and_resolver_servers
  become: yes
  roles:
    - resolver
  tags: 
    - r

- name: Database server
  hosts: db_servers
  become: yes
  roles: 
    - mysql
  tags:
    - db

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
  tags:
    - a

- name: Nginx
  hosts: nginx_and_resolver_servers
  become: yes
  roles: 
    - nginx
  tags:
    - n

- name: Monitoring
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags:
    - p

- name: Monitoring
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags:
    - g

- name: Logging
  hosts: influxdb
  become: yes
  roles:
    - influxdb
  tags:
    - l

- name: Pinger
  hosts: pinger
  become: yes
  roles:
    - pinger
  tags:
    - pi
