---
- name: Init
  hosts: all
  become: yes
  roles:
    - init
  tags: 
    - i
    - b

- name: DNS server
  hosts: dns_servers
  gather_facts: yes
  become: yes
  roles:
    - bind
  tags:
    - b

- name: Resolver service
  hosts: nginx_and_resolver_servers
  gather_facts: yes
  become: yes
  roles:
    - resolver
  tags: 
    - r

- name: Prometheus
  hosts: prometheus
  gather_facts: yes
  become: yes
  roles:
    - prometheus
  tags:
    - p

- name: Docker
  hosts: docker
  gather_facts: yes
  become: yes
  roles:
    - docker
  tags:
    - d

- name: Monitoring
  hosts: grafana
  gather_facts: yes
  become: yes
  roles:
    - grafana
  tags:
    - g

- name: Database server
  hosts: db_servers
  gather_facts: yes
  become: yes
  roles: 
    - mysql
  tags:
    - db
    - app

- name: Agama
  hosts: web_servers
  gather_facts: yes
  become: yes
  roles:
    - agama
  tags:
    - a
    - app

- name: Web server
  hosts: web_servers
  gather_facts: yes
  become: yes
  roles:
    - uwsgi
    - keepalived
    - haproxy
  tags:
    - w
    - app

- name: Nginx
  hosts: nginx_and_resolver_servers
  gather_facts: yes
  become: yes
  roles: 
    - nginx
  tags:
    - n

- name: Logging
  hosts: influxdb
  gather_facts: yes
  become: yes
  roles:
    - influxdb
  tags:
    - l

- name: Pinger
  hosts: pinger
  gather_facts: yes
  become: yes
  roles:
    - pinger
  tags:
    - pi
