---
- name: Init
  hosts: all
  become: yes
  roles:
    - init
  tags: 
    - i

- name: DNS server
  hosts: dns_servers
  become: yes
  roles:
    - bind
  tags:
    - b

- name: Resolver service
  hosts: nginx_and_resolver_servers
  become: yes
  roles:
    - resolver
  tags: 
    - r

- name: Database server
  hosts: db_servers
  become: yes
  roles: 
    - mysql
  tags:
    - db

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
  tags:
    - a

- name: Nginx
  hosts: nginx_and_resolver_servers
  become: yes
  roles: 
    - nginx
  tags:
    - n

- name: Monitoring
  hosts: monitoring
  become: yes
  roles:
    - prometheus
    - grafana
  tags:
    - m

# - name: Deploy Grafana Dashboard
#   hosts: monitoring
#   tasks:
#     - name: Copy main.json to remote host
#       copy:
#         src: "{{ playbook_dir }}/roles/grafana/files/main.json"
#         dest: /var/lib/grafana/main.json

#     - name: Create Grafana Dashboard
#       uri:
#         url: http://{{ hostvars[inventory_hostname].public_url }}:{{ hostvars[inventory_hostname].ansible_port | regex_search('^[0-9]{2}')  }}80/grafana/api/dashboards/db
#         method: POST
#         body: "{{ lookup('file', '{{ playbook_dir }}/roles/grafana/files/main.json') }}" 
#         body_format: json
#         headers:
#           Content-Type: "application/json"
#           Authorization: "Basic SmVzeWEtbzp0b2pp"
#         status_code: 200
#         validate_certs: no
#       delegate_to: localhost
#   tags:
#     - gd
