---

# MySQL
- name: Install MySQL server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Override MySQL configuration file
  ansible.builtin.copy:
    src: files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Ensure MySQL service is enabled and running
  ansible.builtin.service: 
    name: mysql
    state: started
    enabled: true

- name: Install MySQL module for Python 3.X if not installed
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  when: "'3' in ansible_python_version"
  tags:
    - install_mysql_module

- name: Create MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - create_mysql_user

# MySQL exporter
- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Create MySQL user for exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create .my.cnf file
  template:
    src: my.cnf.j2
    dest: "/var/lib/prometheus/.my.cnf"
    owner: prometheus
    group: prometheus
    mode: '0600'
  notify: Restart MySQL exporter

- name: flush
  ansible.builtin.meta: flush_handlers

- name: Ensure MySQL exporter service is started and enabled
  systemd:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
  notify: Restart MySQL exporter

# Backup
- name: Create mysql directory, created and owned by backup
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'
    mode: '0744'

- name: Create MySQL user backup with LOCK TABLES, SELECT privileges on agama database
  mysql_user:
    name: '{{ backup_user }}'
    host: "%"
    password: "{{ mysql_backup_user_password }}"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create .my.cnf file for user 'backup'
  template:
    src: my_backup.cnf.j2
    dest: /home/backup/.my.cnf
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'
    mode: '700'

- name: Add a MySQL cron tab file
  ansible.builtin.template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup
