---
- name: Stop systemd-resolved service
  service:
    name: systemd-resolved
    state: stopped

- name: Disable systemd-resolved service on boot
  service:
    name: systemd-resolved
    enabled: no

- name: Generate and copy resolv.conf file
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: "0644"
    