---
- name: Ensure the 'pinger' user exists
  user:
    name: pinger
    state: present
    shell: /bin/bash
    home: /home/pinger

- name: Install fping
  apt:
    name: fping
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Create /etc/pinger directory
  file:
    path: /etc/pinger
    state: directory
    mode: "0755"

- name: Copy pinger bash script
  template:
    src: pinger.j2
    dest: /usr/local/bin/pinger
    mode: "0755"
  notify: Restart pinger

- name: Copy pinger configuration
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - Restart pinger

- name: Copy pinger service unit
  template:
    src: pinger.service.j2
    dest: /etc/systemd/system/pinger.service
  notify:
    - Restart pinger
    - Reload systemd

- name: flush
  meta: flush_handlers

- name: Start and enable the pinger service
  systemd:
    name: pinger.service
    state: started
    enabled: yes
