---
- name: Restart InfluxDB
  service:
    name: influxdb
    state: restarted

- name: Restart Telegraf
  systemd:
    name: telegraf
    state: restarted
  
- name: Reload systemd
  systemd:
    daemon_reload: yes
