---
- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Copy Prometheus service configuration
  template:
    src: prometheus_service.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus

- name: Ensure Prometheus started and enabled
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
