---
- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart MySQL exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_host: "{{ mysql_host }}"
    primary_password: "{{ mysql_replica_password }}"
    primary_user: replication
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
  no_log: true
  