---
- name: Install Bind9 package
  ansible.builtin.apt: 
    name: bind9
    state: present

- name: Ensure Bind9 is enabled and running
  ansible.builtin.systemd:
    name: bind9
    enabled: true
    state: started

- name: Ensure DNS forwarders are configured
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: "{{ named_conf_file_path }}"
  notify: Restart Bind9 service

- name: Ensure DNS forwarders are configured
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: "{{ named_conf_local_file_path }}"
  notify: Restart Bind9 service

- name: Generate and copy master zone file
  ansible.builtin.template:
    src: "master_zone.j2"
    dest: "{{ zone_file_path }}"
    owner: root
    group: bind
    mode: "0644"
  notify: Restart Bind9 service

# - name: Check what variables were collected
#   ansible.builtin.debug:
#     msg: 
#       - "vm name: {{ vm_name }} "
#       - "vm name 2: {{ vm_name2 }} "
#       - "ip: {{ hostvars[vm_name]['ansible_default_ipv4']['address'] }}"
