---

# Cache update
- name: Update APT cache
  apt:
    cache_valid_time: 86400

# Enable Prometheus node exporters
- name: Install Prometheus node exporter
  apt:
    name: prometheus-node-exporter
    state: present
  notify:
    - Restart Node Exporter service

- name: Start and enable Prometheus node exporter
  systemd:
    name: prometheus-node-exporter
    enabled: yes
    state: started

# Certificates Update
- name: Ensure ca-certificates version is 20230311ubuntu0.20.04.1 or newer
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

# Rsyslog configuration
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Create a custom rsyslog configuration file
  copy:
    content: |
      *.* @{{ influxdb }}:{{ telegraf_udp_port }};RSYSLOG_SyslogProtocol23Format
    dest: /etc/rsyslog.d/99-telegraf.conf
  notify:
    - Restart rsyslog

- name: Ensure rsyslog service is started and enabled
  service:
    name: rsyslog
    state: started
    enabled: yes

# Backup
- name: Create backup user
  user:
    name: '{{ backup_user }}'
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: true

- name: Create file with known hosts
  template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'

- name: Create restore directory, created and owned by backup
  file:
    path: /home/backup/restore
    state: directory
    owner: '{{ backup_user }}'
    group: '{{ backup_user }}'
    mode: '0744'

# Duplicity tool
- name: Install Duplicity package from Ubuntu APT repository
  apt:
    name: duplicity
    state: present

# Directory for downloading packages
- name: Create a directory for downloads
  file:
    path: /opt/downloads
    state: directory
