- name: Download Telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.28.2-1_amd64.deb 
    dest: /opt/downloads/telegraf_1.28.2_amd64.deb
    checksum: "sha256:e074b612e863d517d8908107352333933b3a26f1746c9840d6bc2c3d2463df70"

- name: Install Telegraf
  apt:
    deb: /opt/downloads/telegraf_1.28.2_amd64.deb
    state: present

- name: Configure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - Restart Telegraf

- name: Ensure Telegraf started and enabled
  service:
    name: telegraf
    state: started
    enabled: true
